### ISSUE TITLE
Bug - No option for phone input, ends with error

### ISSUE THREAD

**Issue by tissole** [m4mallu/Pyrogram-V2-SessionStringMaker#1]
I installed all dependencies, I had run the script, I provided the API ID, and API HASH, after that it gives me this error:
`Invalid Id/Hash/Mobile Number (Mobile number should be in international format).`
But there was no option to input phone number, the error appears immediately after I input the API HASH.

**Comment by m4mallu** [comment]
This is an exception caused by unable to the start your client with your provided `API ID and API HASH`. It's not an issue with the code. **Check your variable and try again**. currently I'm using the same with out any errors.

**Comment by tissole** [comment]
This is very weird, I checked again, same error. I checked even with other credentials, same.  Windows 11, Python 3.10.6, I created an venv, activate it and I installed req., then py maker.py.

**Comment by m4mallu** [comment]
Fixed  https://github.com/m4mallu/Pyrogram-V2-SessionStringMaker/commit/9438934f0da67c3dd4c0b83ef17786c27a4c8d1b : Just try now.

**Comment by tissole** [comment]
Yeah, it is working now. Thanks! 👍
